ignore_colors = [
	[0, 0, 0, 0],
	[0, 0, 0, 255], # filter all black
]

version = 11

[priorities]
"1" = 1
"2" = 5
"3" = 10
"4" = 15

[[structure]]
name = "TransPlaceStripe"
file = "images/TransPlaceStripeDefend.png"
startx = 701
starty = 430
priority = 3

[[structure]]
name = "TransFlagDefense"
file = "images/TransPlaceDefend.png"
startx = 687
starty = 430
priority = 2

[[structure]]
name = "TransPlaceWhite"
file = "images/TransPlaceWhite.png"
startx = 688
starty = 433
priority = 1

[[structure]]
name = "TransPlaceGrey"
file = "images/TransPlaceGrey.png"
startx = 689
starty = 434
priority = 1
